###
HEAD https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{licenseKey}}&suffix=tar.gz

###
HEAD  https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{licenseKey}}&suffix=tar.gz.sha256

